[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && ./gradlew bootRun --args='--spring.profiles.active=prod'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"
